version: 2
sources:
  - name: postgres__employees
    schema: postgres__employees
    description: "Source data loaded by Fivetran"
    tables:
      - name: employee_count
        description: "Raw employee_count from source system"
