version: 2

sources:
  - name: employees
    schema: postgres__employees
    description: Employee data in Redshift
    tables:
      - name: employee
        description: Employee records
        columns:
          - name: emp_no
            description: Unique employee identifier
            tests:
              - unique
              - not_null
          - name: birth_date
            description: Employee birth date
          - name: first_name
            description: Employee first name
          - name: last_name
            description: Employee last name
          - name: gender
            description: Employee gender (M/F)
          - name: hire_date
            description: Date when employee was hired
