version: 2

sources:
  - name: postgres__employees
    schema: postgres__employees
    tables:
      - name: employee
        columns:
          - name: id
            data_type: bigint
            description: "Primary key"
          - name: birth_date
            data_type: date
            description: "Employee birth date"
          - name: first_name
            data_type: varchar(14)
            description: "Employee first name"
          - name: last_name
            data_type: varchar(16)
            description: "Employee last name"
          - name: gender
            data_type: varchar(1)
            description: "Employee gender"
          - name: hire_date
            data_type: date
            description: "Employee hire date"